version: '3.8'
name: FloodWarner

networks:
  model_network:
    driver: bridge

volumes:
  ollama:

services:

  FloodReader:
    image: floodwarner/floodreader:1.0.0
    build:
      context: .
      dockerfile: DockerFiles/ModelServer.Dockerfile
    container_name: FloodReader
    restart: unless-stopped
    ports:
    - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    
    # networks:
    #   - model_network
